export type NativeUsage = {
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  cachedTokens?: number;
  cachedInputTokens?: number;
  imageCount?: number;
  generatedImageCount?: number;
  imageWidth?: number;
  imageHeight?: number;
  imageBytes?: number;
  imageSize?: number;
  audioSeconds?: number;
  audioMinutes?: number;
  videoSeconds?: number;
  generatedSeconds?: number;
  characterCount?: number;
  inputBytes?: number;
  outputBytes?: number;
  trackCount?: number;
  videoCount?: number;
  generatedAudioMinutes?: number;
  inputCharacters?: number;
  providerNativeUnitAmount?: number;
  [key: string]: number | undefined;
};

export type UsageRecord = {
  usageId: string;
  requestId: string;
  correlationId: string;
  actorTrustId: string;
  callerId: string;
  entitySlug?: string;
  tenantId?: string;
  applicationId?: string;
  receiptId?: string;
  capability?: string;
  privacyClass?: string;
  provider: string;
  providerId?: string;
  model?: string;
  modelId?: string;
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  nativeUsage?: NativeUsage;
  providerRequestId?: string;
  pricingVersion?: string | null;
  currency?: string | null;
  estimatedProviderCost?: number | null;
  actualProviderCost?: number | null;
  /** Provider-native generation units. Never Digi AI credits. */
  providerNativeUnits?: { type: string; amount: number } | null;
  /** Phase 2A is unpriced. Never a fake credit balance. */
  digiAiUnits: null;
  errorClass?: string;
  startedAt?: string;
  completedAt?: string;
  latencyMs: number;
  success: boolean;
  status?: "completed" | "failed" | "provider_unavailable" | "unsupported_capability" | "processing";
  createdAt: string;
};

export type RequestReceipt = {
  receiptId: string;
  requestId: string;
  correlationId: string;
  actorTrustId: string;
  callerId: string;
  entitySlug?: string;
  tenantId?: string;
  operation: string;
  sourcesAccessed: string[];
  provider?: string;
  model?: string;
  capability?: string;
  routeExplanation?: string;
  resultStatus: "completed" | "failed" | "unauthorized" | "provider_unavailable" | "source_unavailable" | "unsupported_capability" | "processing";
  usageId?: string;
  idempotencyKey?: string;
  resultSnapshot?: {
    answer?: string;
    media?: unknown;
    finishState?: string;
    canonicalAssetReference?: string;
    speech?: unknown;
    providerOperationId?: string;
  };
  createdAt: string;
};
